/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-10-19 09:17:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DAO.PromotionDAO;
import Modal.Promotion;
import Modal.Customer;
import Modal.Product;
import DAO.ProductDAO;
import DAO.BrandDAO;
import java.util.ArrayList;
import Modal.Category;
import Modal.Brand;
import DAO.CategoryDAO;
import java.util.List;
import java.text.DecimalFormat;
import DAO.CustomerDAO;
import Modal.CustomerSession;
import Modal.Product;
import DAO.ProductDAO;
import DAO.BrandDAO;
import java.util.ArrayList;
import Modal.Category;
import Modal.Brand;
import Modal.Customer;
import Modal.Cart;
import DAO.CategoryDAO;
import java.util.List;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Views/header.jsp", Long.valueOf(1591181526000L));
    _jspx_dependants.put("/Views/Footer.jsp", Long.valueOf(1591193272000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Modal.Brand");
    _jspx_imports_classes.add("DAO.CustomerDAO");
    _jspx_imports_classes.add("Modal.Promotion");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("Modal.Category");
    _jspx_imports_classes.add("Modal.Cart");
    _jspx_imports_classes.add("Modal.Customer");
    _jspx_imports_classes.add("DAO.BrandDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("DAO.PromotionDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Modal.CustomerSession");
    _jspx_imports_classes.add("DAO.ProductDAO");
    _jspx_imports_classes.add("Modal.Product");
    _jspx_imports_classes.add("DAO.CategoryDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Mua hàng trực tuyến với 500AE</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.4.1/css/all.css\"\n");
      out.write("\tintegrity=\"sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\n");
      out.write("\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\n");
      out.write("\tintegrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"\n");
      out.write("\tintegrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"../Css/Fstyle.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("$(function () {\n");
      out.write("    $(\".loadMore1\").slice(0, 4).show();\n");
      out.write("    $(\".loadMore2\").slice(0, 4).show();\n");
      out.write("    var count1=  $(\".loadMore1\").length\n");
      out.write("    var count2=  $(\".loadMore2\").length\n");
      out.write("    $(\"#loadMore1\").click(function(){\n");
      out.write("        $(\".loadMore1:hidden\").slice(0, count1).slideDown();\n");
      out.write("        $(\"#loadMore1\").css(\"display\",\"none\")\n");
      out.write("    });\n");
      out.write("    $(\"#loadMore2\").click(function(){\n");
      out.write("        $(\".loadMore2:hidden\").slice(0, count2).slideDown();   \n");
      out.write("        $(\"#loadMore2\").css(\"display\",\"none\")\n");
      out.write("    });\n");
      out.write("});\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\"\n");
      out.write("\tintegrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\"\n");
      out.write("\tcrossorigin=\"anonymous\"> \n");
      out.write(" <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.4.1/css/all.css\"\n");
      out.write("\tintegrity=\"sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("\t\n");
      out.write("<link rel=\"stylesheet\" href=\"../Css/Fstyle.css\">\n");
      out.write("<script src=\"../Js/header.js\"></script>\n");
      out.write("<script>\n");
      out.write("\t$(document).ready(function() {\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#btnSearch\").click(function() {\n");
      out.write("\t\t\tvar textSearch = $(\"#text-Search\").val()\n");
      out.write("\t\t\tvar flag=0\n");
      out.write("\t\t\tif(textSearch.trim()==''){\n");
      out.write("\t\t\t\tflag=1\n");
      out.write("\t\t\t\twindow.location.href = \"http://localhost:8080/ShopDienTuOnline/Views/Home.jsp\"\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif(flag==0){\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t\ttype : \"post\",\n");
      out.write("\t\t\t\t\t\turl : \"/ShopDienTuOnline/searchServlet\",\n");
      out.write("\t\t\t\t\t\tdata : {\n");
      out.write("\t\t\t\t\t\t\t\ttextSearch : textSearch\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\tsuccess : function(response) {\n");
      out.write("\t\t\t\t\t\t\twindow.location.href = \"http://localhost:8080/ShopDienTuOnline/Views/ListofSearch.jsp\"\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t}\n");
      out.write("\t\t})\n");
      out.write("\t\t$(\"#btnLoginHeader\").click(function(){\n");
      out.write("\t\t\t  $('#LoginModal').modal('show')\n");
      out.write("\t\t\t\t $(\"#loginModalClick\").trigger('click')\n");
      out.write("\t\t})\n");
      out.write("\t\t$(\"#btnRegisterHeader\").click(function(){\n");
      out.write("\t\t\t $('#LoginModal').modal('show')\n");
      out.write("\t\t\t $(\"#registerModalClick\").trigger('click')\n");
      out.write("\t\t})\n");
      out.write("\t\t$(\"#btnCustomer\").click(function(){\n");
      out.write("\t\t\t var idCustomer= $(this).attr(\"data-idCustomer\")\n");
      out.write("\t\t\t var nameCustomer= $(this).attr(\"data-nameCustomer\")\n");
      out.write("\t\t\t var phoneCustomer= $(this).attr(\"data-phoneCustomer\")\n");
      out.write("\t\t\t var emailCustomer= $(this).attr(\"data-emailCustomer\")\n");
      out.write("\t\t\t var addressCustomer= $(this).attr(\"data-addressCustomer\")\n");
      out.write("\t\t\t $(\"#textNameCustomer\").val(nameCustomer)\n");
      out.write("\t\t\t if(phoneCustomer=='null'){\n");
      out.write("\t\t\t\t $(\"#textPhoneCustomer\").html('')\n");
      out.write("\t\t\t } else {\n");
      out.write("\t\t\t\t $(\"#textPhoneCustomer\").val(phoneCustomer)\n");
      out.write("\t\t\t }\n");
      out.write("\t\t\t if(phoneCustomer=='null'){\n");
      out.write("\t\t\t\t $(\"#textAddressCustomer\").html('')\t\n");
      out.write("\t\t\t } else {\n");
      out.write("\t\t\t\t $(\"#textAddressCustomer\").val(addressCustomer)\t\n");
      out.write("\t\t\t }\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t $(\"#textEmailCustomer\").val(emailCustomer)\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t $(\"#btnEditCustomer\").val(idCustomer)\n");
      out.write("\t\t\t $('#CustomerModal').modal('show')\n");
      out.write("\t\t\t\t\t$(\"#textNameCustomer\").keypress(function(){\n");
      out.write("\t\t\t\t\t$(\"#name_alertCustomer\").html('')\n");
      out.write("\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t$(\"#textPhoneCustomer\").keypress(function(){\n");
      out.write("\t\t\t\t\t\t$(\"#phone_alertCustomer\").html('') \n");
      out.write("\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t$(\"#textAddressCustomer\").keypress(function(){\n");
      out.write("\t\t\t\t\t\t$(\"#address_alertCustomer\").html('') \n");
      out.write("\t\t\t\t\t})\n");
      out.write("\t\t\t $(\"#btnEditCustomer\").click(function(){\n");
      out.write("\t\t\t\t\t\tvar flag=0\n");
      out.write("\t\t\t\t\t\tvar id= $(\"#btnEditCustomer\").val()\n");
      out.write("\t\t\t\t\t\tvar name= $(\"#textNameCustomer\").val()\n");
      out.write("\t\t\t\t\t\tvar phone= $(\"#textPhoneCustomer\").val()\n");
      out.write("\t\t\t\t\t\tvar address= $(\"#textAddressCustomer\").val()\n");
      out.write("\t\t\t\t\t\tvar dataButton= $(this).attr(\"data-button\")\n");
      out.write("\t\t\t\t\t\t  if(address.trim() ==''){\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#address_alertCustomer\").html('(*)Địa chỉ không được để trống!');\n");
      out.write("\t\t\t\t\t\t\t\tflag=1\n");
      out.write("\t\t\t\t\t\t\t} \n");
      out.write("\t\t\t\t\t\tif(name.trim()==''){\n");
      out.write("\t\t\t\t\t\t\t$(\"#name_alertCustomer\").html(\"(*)Họ và tên không được để trống! \")\n");
      out.write("\t\t\t\t\t\t\tflag=1\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\tif(phone.trim()==''){\n");
      out.write("\t\t\t\t\t\t\t$(\"#phone_alertCustomer\").html(\"(*)Số điện thoại không được để trống! \")\n");
      out.write("\t\t\t\t\t\t\tflag=1\n");
      out.write("\t\t\t\t\t\t} \n");
      out.write("\t\t\t\t\t\tif(phone.trim()!='' && phone.length>12 || phone.length<8){\n");
      out.write("\t\t\t\t         \t$(\"#phone_alertCustomer\").html('(*)Số điện thoại phải trên 8 số và dưới 12 số')\n");
      out.write("\t\t\t\t         \tflag=1;\n");
      out.write("\t\t\t\t         }\n");
      out.write("\t\t\t\t\t\tif(flag==0){\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t\t\t\ttype: \"post\",\n");
      out.write("\t\t\t\t\t\t\t\turl: \"/ShopDienTuOnline/editProfileServlet\",\n");
      out.write("\t\t\t\t\t\t\t\tdata: {\n");
      out.write("\t\t\t\t\t\t\t\t\tid : id,\n");
      out.write("\t\t\t\t\t\t\t\t\tnameCustomer : name,\n");
      out.write("\t\t\t\t\t\t\t\t\tphoneCustomer : phone,\n");
      out.write("\t\t\t\t\t\t\t\t\taddressCustomer : address,\n");
      out.write("\t\t\t\t\t\t\t\t\tdataButton : dataButton\n");
      out.write("\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(response){\n");
      out.write("\t\t\t\t\t\t\t\t\tif(response==\"success\"){\n");
      out.write("\t\t\t\t\t\t\t\t\t\twindow.location.replace(\"http://localhost:8080/ShopDienTuOnline/Views/Home.jsp\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\telse if(response==\"wrong\"){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#address_alertCustomer\").html(\"(*)Đăng kí không thành công! \")\n");
      out.write("\t\t\t\t\t\t\t\t\t} \n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t})\n");
      out.write("\t\t})\n");
      out.write("\t\t\n");
      out.write("\t\t\t$(\"#change-password\").click(function() {\t\n");
      out.write("\t\t\t\t\t\t$(\"#CustomerModal\").modal('hide')\n");
      out.write("\t\t\t\t\t\t$(\"#changePassword\").modal('show')\n");
      out.write("\t\t\t\t\t\t$(\"#oldpass\").keypress(function() {\n");
      out.write("\t\t\t\t\t\t$(\"#passwordResult\").html('');\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t$(\"#newpass\").keypress(function() {\n");
      out.write("\t\t\t\t\t\t\t$(\"#newPasswordResult\").html('');\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t$(\"#renewpass\").keypress(function() {\n");
      out.write("\t\t\t\t\t\t\t$(\"#repasswordResult\").html('');\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t$(\"#resetChange\").click(function(){\n");
      out.write("\t\t\t\t\t\t\t$(\"#oldpass\").val('')\n");
      out.write("\t\t\t\t\t\t\t$(\"#newpass\").val('')\n");
      out.write("\t\t\t\t\t\t\t$(\"#renewpass\").val('')\n");
      out.write("\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t$(\"#btnChange\").click(function(){\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\tvar oldpass= $(\"#oldpass\").val()\n");
      out.write("\t\t\t\t\t\t\t\tvar newpass = $(\"#newpass\").val()\n");
      out.write("\t\t\t\t\t\t\t\tvar renewpass = $(\"#renewpass\").val()\n");
      out.write("\t\t\t\t\t\t\t\tvar dataButton = $(this).attr(\"data-button\")\n");
      out.write("\t\t\t\t\t\t\t\tvar id = $(this).attr(\"data-id\")\n");
      out.write("\t\t\t\t\t\t\t\tvar flag = 0;\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\tif(oldpass.trim()==''){\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#passwordResult\").html('(* Bạn cần phải điền mật khẩu cũ của bạn *)')\n");
      out.write("\t\t\t\t\t\t\t\t\tflag = 1\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\tif(newpass.trim()==''){\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#newPasswordResult\").html('(* Bạn cần phải điền mật khẩu mới *)')\n");
      out.write("\t\t\t\t\t\t\t\t\tflag = 1\n");
      out.write("\t\t\t\t\t\t\t\t}\t\n");
      out.write("\t\t\t\t\t\t\t\tif(renewpass.trim()==''){\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#repasswordResult\").html('(* Bạn cần xác nhận lại mật khẩu *)')\n");
      out.write("\t\t\t\t\t\t\t\t\tflag = 1\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\tif(newpass.trim()!='' && newpass.length < 8 || newpass.length > 50){\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#newPasswordResult\").html('(* Mật khẩu phải >=8 chars và <= 30 kí tự *)')\n");
      out.write("\t\t\t\t\t\t\t\t\tflag = 1\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\tif(newpass.trim() != renewpass.trim()){\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#repasswordResult\").html('(*  Mật khẩu không trùng. Vui lòng xác thực lại *) ')\n");
      out.write("\t\t\t\t\t\t\t\t\tflag = 1\n");
      out.write("\t\t\t\t\t\t\t\t}if(flag == 0){\n");
      out.write("\t\t\t\t\t\t\t\t\t $.ajax({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t \ttype: \"post\",\n");
      out.write("\t\t\t\t\t\t\t\t        \turl:\"/ShopDienTuOnline/editProfileServlet\",\n");
      out.write("\t\t\t\t\t\t\t\t        \tdata:{\n");
      out.write("\t\t\t\t\t\t\t\t        \t\t\tid : id,\n");
      out.write("\t\t\t\t\t\t\t\t        \t\t\toldpass : oldpass,\n");
      out.write("\t\t\t\t\t\t\t\t        \t\t\tnewpass : newpass,\n");
      out.write("\t\t\t\t\t\t\t\t        \t\t\tdataButton : dataButton\n");
      out.write("\t\t\t\t\t\t\t\t        \t\t},\n");
      out.write("\t\t\t\t\t\t\t\t            success: function (response) {\n");
      out.write("\t\t\t\t\t\t\t\t            \tif(response == \"success\"){\n");
      out.write("\t\t\t\t\t\t\t\t            \t\t$(\"#changePassword\").modal('hide')\n");
      out.write("\t\t\t\t\t\t\t\t            \t\t$(\"#changeSuccess\").modal('show')\n");
      out.write("\t\t\t\t\t\t\t\t            \t\t\n");
      out.write("\t\t\t\t\t\t\t\t            \t\t$('#btnSuccess').click(function(){\n");
      out.write("\t\t\t\t\t\t\t\t            \t\t\t$('.modal-backdrop').remove()\n");
      out.write("\t\t\t\t\t\t\t\t            \t\t})\t\n");
      out.write("\t\t\t\t\t\t\t\t            \t}\n");
      out.write("\t\t\t\t\t\t\t\t            \telse if (response == \"wrong\"){\n");
      out.write("\t\t\t\t\t\t\t\t            \t\t$(\"#passwordResult\").html('(* Mật khẩu hiện tại không đúng *)')\n");
      out.write("\t\t\t\t\t\t\t\t            \t}\n");
      out.write("\t\t\t\t\t\t\t\t            \telse if (response == \"fail\"){\n");
      out.write("\t\t\t\t\t\t\t\t            \t\t$(\"#passwordResult\").html('(* Đã có lỗi xảy ra *)')\n");
      out.write("\t\t\t\t\t\t\t\t            \t}\n");
      out.write("\t\t\t\t\t\t\t\t            } \n");
      out.write("\t\t\t\t\t\t\t\t            \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#btnLogout\").click(function(){\n");
      out.write("\t\t\twindow.location.replace(\"http://localhost:8080/ShopDienTuOnline/logOutServlet?role=customer\");\n");
      out.write("\t\t})\n");
      out.write("\t\t\n");
      out.write("})\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- -------Khai báo phương thức------------ -->\n");
      out.write("\t");

		CategoryDAO categoryDAO = new CategoryDAO();
		Category category = new Category();
		BrandDAO brandDAO = new BrandDAO();
		Brand brand = new Brand();
		Customer customer= new Customer();
		CustomerDAO customerDAO= new CustomerDAO();

		Cart cart = (Cart) session.getAttribute("cart");
		if (cart == null) {
			cart = new Cart();
			session.setAttribute("cart", cart);
			
		}
		String register = "Đăng kí";
		String login = "Đăng nhập";
		Customer user = (Customer) session.getAttribute("customerSession");

		if (user != null) {
			customer= customerDAO.customerByID(user.getId());
			register = customer.getName();
			login = "Đăng xuất";
		}
	
      out.write("\n");
      out.write("<!-- Header - start -->\n");
      out.write("<header class=\"header container\" id=\"header-content\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Logo, Shop-menu - start -->\n");
      out.write("\t\t<div class=\"header-middle \">\n");
      out.write("\t\t\t\t<div class=\"header-middle-cont\">\n");
      out.write("\t\t\t\t\t<div class=\"toplogo\">\n");
      out.write("\t\t\t\t\t\t<a href=\"Home.jsp\"> <img src=\"../img/header/logo.png\"\n");
      out.write("\t\t\t\t\t\t\talt=\"Electronic Store\">\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"shop-menu\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"topauth\"><a");
if(user==null){ 
      out.write(" id=btnRegisterHeader");
}else {
								
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t     id=btnCustomer data-idCustomer=\"");
      out.print(customer.getId());
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t     data-nameCustomer=\"");
      out.print(customer.getName());
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t     data-phoneCustomer=\"");
      out.print(customer.getPhone());
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t     data-addressCustomer=\"");
      out.print(customer.getAddress() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t     data-emailCustomer=\"");
      out.print(customer.getEmail() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t     \n");
      out.write("\t\t\t\t\t\t\t      ");
} 
      out.write("> <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-user\"></i> <span class=\"shop-menu-ttl\">");
      out.print(register);
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t</a> \n");
      out.write("\t\t\t\t\t\t\t<a ");
if(user==null){ 
      out.write(" id=\"btnLoginHeader\"");
}else{ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\tid=\"btnLogout\"");
} 
      out.write(" \n");
      out.write("\t\t\t\t\t\t\t\t> <span class=\"shop-menu-ttl\">");
      out.print(login);
      out.write("</span>\n");
      out.write("\t\t\t\t\t\t\t</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"h-cart\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"Cart.jsp\"> <i class=\"fa fa-shopping-cart\"></i> <span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"shop-menu-ttl\">Giỏ hàng</span> (<b>");
      out.print(cart.countItem());
      out.write("</b>)\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t<!-- Logo, Shop-menu - end -->\n");
      out.write("\n");
      out.write("\t<!-- Topmenu - start -->\n");
      out.write("\t<div class=\"header-bottom\">\n");
      out.write("\t\t<div >\n");
      out.write("\t\t\t<nav class=\"topmenu\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Catalog menu - start -->\n");
      out.write("\t\t\t\t<div class=\"topcatalog\">\n");
      out.write("\t\t\t\t\t<a class=\"topcatalog-btn\" ><span>Tất cả</span> Danh mục</a>\n");
      out.write("\t\t\t\t\t<ul class=\"topcatalog-list\">\n");
      out.write("\t\t\t\t\t\t");

								List<Brand> listBrand = new ArrayList<>();
								listBrand = BrandDAO.listAllBrand();
								for (int i = 0; i < listBrand.size(); i++) {
									int idBrand = listBrand.get(i).getId();
									String nameBrand = listBrand.get(i).getName();
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<li><a\n");
      out.write("\t\t\t\t\t\t\t\thref=\"Brand.jsp?brandID=");
      out.print(idBrand);
      out.write('"');
      out.write('>');
      out.print(nameBrand);
      out.write("</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

								}
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- Catalog menu - end -->\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Main menu - start -->\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"mainmenu\">\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"index.html\" >\n");
      out.write("\t\t\t\t\t\t\tHome\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<li >\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" >\n");
      out.write("\t\t\t\t\t\t\tProduct \n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\tHỗ trợ khách hàng\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">\n");
      out.write("\t\t\t\t\t\t\tDịch vụ Ưu Đãi\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t");
if(user!=null){ 
      out.write("\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"MyOrder.jsp?idCustomer=");
      out.print(user.getId());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\tĐơn hàng của tôi\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<!-- Main menu - end -->\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Search - start -->\n");
      out.write("\t\t\t\t<div class=\"topsearch\">\n");
      out.write("\t\t\t\t<input id=\"text-Search\" type=\"text\" \n");
      out.write("\t\t\t\t");
 
				if(session.getAttribute("textSearch")==null){ 
      out.write(" \n");
      out.write("\t\t\t\tplaceholder=\"TÌM KIẾM...\"\n");
      out.write("\t\t\t\t");
} else { 
					String textSearch= (String) session.getAttribute("textSearch");
				
      out.write("\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(textSearch );
      out.write("\"\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");

				} 
      out.write("\n");
      out.write("\t\t\t\t>\n");
      out.write("\t\t\t\t\t<a id=\"btnSearch\" class=\"topsearch-btn\" href=\"#\"><i class=\"fa fa-search\"></i></a>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- Search - end -->\n");
      out.write("\n");
      out.write("\t\t\t</nav>\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- Topmenu - end -->\n");
      out.write("<!-- -----Modal--------- -->\n");
      out.write("<div class=\"modal fade\" id=\"LoginModal\" role=\"dialog\" style=\"display: none\">\n");
      out.write("\t\t\t<div class=\"modal-dialog modal-center\" role=\"document\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=modal-body>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav nav-tabs\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a id=\"loginModalClick\" data-toggle=\"tab\" href=\"#login\">ĐĂNG\n");
      out.write("\t\t\t\t\t\t\t\t\t\tNHẬP</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a id=\"registerModalClick\" data-toggle=\"tab\" href=\"#register\">ĐĂNG KÍ</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab-content\">\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"login\" class=\"tab-pane fade in active\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Chào mừng tới 500AE Shop! Đăng nhập ngay</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\" formLogin\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form id=\"form-login\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label>E-mail </label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Vui lòng nhập email của bạn\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"textEmail\" class=\"form-control\"> <span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"alert\" id=\"email_alert\"> </span>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label>Password </label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Vui lòng nhập mật khẩu của bạn\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"password\" id=\"textPassword\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"alert\" id=\"pass_alert\"></span>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a id=\"forgot-password\" href=\"#\" style=\"float:left\">Quên mật khẩu?</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn-login\" type=\"button\" id=\"btnLogin\">Đăng\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnhập</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clear-float\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t<div id=\"register\" class=\"tab-pane fade\">\n");
      out.write("\t\t\t<h3>Tạo tài khoản 500AE</h3>\n");
      out.write("\t\t<div class=\" formLogin\">\n");
      out.write("\t\t\t<form id=\"form-register\">\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("\t\t\t\t<label >Họ và tên</label><input type=\"text\" id=\"textNameRegister\" placeholder=\"Vui lòng nhập họ tên của bạn\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t<span class= \"alert\" id= \"name_alertRegister\"></span> \n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("\t\t\t\t<label >E-mail </label><input type=\"text\" id=\"textEmailRegister\" placeholder=\"Vui lòng nhập email của bạn\" class=\"form-control\" >\n");
      out.write("\t\t\t\t\t<span class= \"alert\" id= \"email_alertRegister\"> </span> \n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("\t\t\t\t<label >Mật khẩu </label><input id=\"textPasswordRegister\" type=\"password\"  placeholder=\"Vui lòng nhập mật khẩu của bạn\" class=\"form-control\" >\n");
      out.write("\t\t\t\t\t<span class= \"alert\" id= \"pass_alertRegister\"> </span> \n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\t\t\t\t<label >Nhập lại Mật khẩu </label>\n");
      out.write("\t\t\t\t<input type=\"password\" id=\"textRePasswordRegister\" placeholder=\"Vui lòng nhập lại mật khẩu của bạn\" class=\"form-control\" >\n");
      out.write("\t\t\t\t\t\t<span class= \"alert\" id= \"rePass_alertRegister\"> </span> \n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<button class=\"btn-login\" type=\"button\" id=\"btnRegister\" >Đăng kí</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<div class=\"clear-float\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"modal fade\" id=\"forgotModal\" role=\"dialog\" style=\"display: none;top:150px\">\n");
      out.write("\t\t<div class=\"modal-dialog modal-center\" role=\"document\">\n");
      out.write("\t\t\t<div class=\"modal-content\" style=\"border: 1px solid lightgray;width:80%;margin:auto\">\n");
      out.write("\t\t\t<div class=\"modal-header\" style=\"    background-color: aliceblue\">\n");
      out.write("\t\t\t\t\t\t<h3 class=\"modal-title\" style=\"color:black\" >Quên Mật Khẩu</h3>\n");
      out.write("\t\t\t\t\t\t <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t<p style=\"font-size:16px\">Nhập tài khoản mà bạn đã quên mật khẩu</p>\n");
      out.write("\t\t\t\t\t<input type=\"text\" style=\"width:100%;border-radius: 5px; border:1px solid lightgray;padding:5px\" \n");
      out.write("\t\t\t\t\tplaceholder=\"E-mail\" id=\"emailForgot\" />\n");
      out.write("\t\t\t\t\t<span class=\"alert\" style=\"font-size:15px; padding:20px 0px\" id=\"alert-emailForgot\"></span>\n");
      out.write("\t\t\t\t\t<span class=\"alert\" style=\"font-size:15px; color:green; padding: 20px 0px\" id=\"alert-emailSuccess\"></span>\n");
      out.write("\t\t\t\t\t<div class=modal-footer>\n");
      out.write("\t\t\t\t\t<button data-button=\"forgotPassCustomer\" class=\"btn btn-primary\" id=\"sendForgot\">Gửi</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div> \n");
      out.write("\t<div class=\"modal fade\" id=\"CustomerModal\" role=\"dialog\" style=\"display: none;top: 100px;\">\n");
      out.write("\t\t\t<div class=\"modal-dialog modal-center\" role=\"document\" >\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=modal-body>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\" formLogin\">\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 style=\"text-align:center;margin-bottom:10px; margin-top:10px\">HỒ SƠ KHÁCH HÀNG</h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("\t\t\t\t<label >Họ Và Tên</label><input type=\"text\" id=\"textNameCustomer\" placeholder=\"Vui lòng nhập họ tên của bạn\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t<span class= \"alert\" id= \"name_alertCustomer\"></span> \n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("\t\t\t\t<label >Số Điện Thoại </label><input type=\"text\" id=\"textPhoneCustomer\" placeholder=\"Vui lòng nhập SDT của bạn\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t<span class= \"alert\" id= \"phone_alertCustomer\"></span> \n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("\t\t\t\t<label >E-mail </label><input type=\"text\" id=\"textEmailCustomer\" readonly placeholder=\"Vui lòng nhập email của bạn\" class=\"form-control\" >\n");
      out.write("\t\t\t\t\t<span class= \"alert\" id= \"email_alertCustomer\" > </span> \n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\n");
      out.write("\t\t\t\t<label >Địa Chỉ </label><input type=\"text\" id=\"textAddressCustomer\" placeholder=\"Vui lòng nhập địa chỉ của bạn\" class=\"form-control\" >\n");
      out.write("\t\t\t\t\t<span class= \"alert\" id= \"address_alertCustomer\"> </span> \n");
      out.write("\n");
      out.write("\t\t\t</div> \n");
      out.write("\t\t\t<a id=\"change-password\" href=\"#\" style=\"float:left\">Thay đổi mật khẩu</a>\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<button data-button=\"editProfileCustomer\" class=\"btn-login\" type=\"button\" id=\"btnEditCustomer\">Chỉnh Sửa</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"clear-float\"></div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("   </div>\n");
      out.write("   \t<div class=\"modal fade\" id=\"changePassword\" role=\"dialog\">\n");
      out.write("\t\t<div class=\"modal-dialog modal-center\" role=\"document\" style=\"top: 100px;\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"    background-color: aliceblue;\">\n");
      out.write("\t\t\t\t\t<h3 class=\"modal-title\">Thay đổi mật khẩu</h3>\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\t\t\t\t\t<label>Mật khẩu hiện tại</label>\n");
      out.write("\t\t\t\t\t<input type=\"password\" \n");
      out.write("\t\t\t\t\tid=\"oldpass\" placeholder=\"Nhập mật khẩu hiện tại\">\n");
      out.write("\t\t\t\t\t<span class= \"alert\" id= \"passwordResult\" style=\"padding:0; margin:0\"></span>\n");
      out.write("\t\t\t\t\t</div> \n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\t\t\t\t\t<label>Mật khẩu mới</label>\n");
      out.write("\t\t\t\t\t<input type=\"password\"  id=\"newpass\" placeholder=\"Nhập mật khẩu mới\">\n");
      out.write("\t\t\t\t\t<span class= \"alert\" id=\"newPasswordResult\"  style=\"padding:0; margin:0\"></span> \n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\" style=\"margin:0\">\n");
      out.write("\t\t\t\t\t<label>Nhập lại mật khẩu mới</label>\n");
      out.write("\t\t\t\t\t<input type=\"password\" \n");
      out.write("\t\t\t\t\tid=\"renewpass\" placeholder=\"Nhập lại mật khẩu\">\n");
      out.write("\t\t\t\t\t\t<span class= \"alert\" id= \"repasswordResult\"  style=\"padding:0; margin:0\"> </span> \n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t<button ");
 if(user!=null){ 
      out.write(" data-id=\"");
      out.print(user.getId() );
 } 
      out.write("\" data-button=\"changePassCustomer\" type=\"button\" id=\"btnChange\" class=\"btn btn-primary\">Đồng Ý</button>\n");
      out.write("\t\t\t\t\t<button id=\"resetChange\" class=\"btn \">Phục Hồi</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"modal fade\" id=\"changeSuccess\" role=\"dialog\">\n");
      out.write("\t\t<div class=\"modal-dialog modal-center\" role=\"document\"  style=\"top: 100px;\">\n");
      out.write("\t\t\t<div class=\"modal-content\" style=\"border: 1px solid lightgray;width:80%;margin:auto\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"    background-color: aliceblue;\">\n");
      out.write("\t\t\t\t\t<h3 class=\"modal-title\">Mật Khẩu</h3>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t<p>Thay đổi mật khẩu thành công!</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"btnSuccess\" class=\"btn btn-primary\"\n");
      out.write("\t\t\t\t\t\tdata-dismiss=\"modal\">OK</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("</header>\n");
      out.write("<!-- Header - end -->\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t<section>\n");
      out.write("\n");
      out.write("\t\t<div id=\"section-content\" class=\" container\">\n");
      out.write("\t\t\t<div class=\"home row\">\n");
      out.write("\t\t\t\t<div class=\"img-slider col-lg-8 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("\t\t\t\t\t<div id=\"carousel-indicators\" class=\"carousel slide\"\n");
      out.write("\t\t\t\t\t\tdata-ride=\"carousel\">\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-inner\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-item active\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"d-block w-100\"\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"../img/quangcao/800-300-800x300.png\"\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"not found\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"d-block w-100\"\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"../img/quangcao/A11-800-300-800x300.png\" alt=\"not found\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"d-block w-100\"\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"../img/quangcao/800-300-800x300-4.png\" alt=\"not found\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<a class=\"carousel-control-prev\" href=\"#carousel-indicators\"\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-slide=\"prev\"> <span\n");
      out.write("\t\t\t\t\t\t\tclass=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t\t\t\t\t</a> <a class=\"carousel-control-next\" href=\"#carousel-indicators\"\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-slide=\"next\"> <span\n");
      out.write("\t\t\t\t\t\t\tclass=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"hinh-quangcao\">\n");
      out.write("\t\t\t\t\t\t<img style=\"width: 100%\"\n");
      out.write("\t\t\t\t\t\t\tsrc=\"../img/quangcao/quangcao.jpeg\" alt=\"\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"slider-right col-lg-4 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<img alt=\"\" src=\"../img/quangcao/sticky-a51-398-110-398x110.png\">\n");
      out.write("\t\t\t\t\t<img alt=\"\" src=\"../img/quangcao/2ED22C0B-154B-4108-B279-0793C8E4B76C-398x110.png\">\n");
      out.write("\t\t\t\t\t<img alt=\"\" src=\"../img/quangcao/Rightbanner.jpg\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"info\">\n");
      out.write("\t\t\t\t");

				DecimalFormat formatter = new DecimalFormat("###,###");
				ProductDAO productDAO = new ProductDAO();
				Product product = new Product();
				List<Product> listProduct = new ArrayList<>();
				Promotion promotion= new Promotion();
				PromotionDAO promotionDAO= new PromotionDAO();
				promotion= promotionDAO.promotionbyCurrentDate();
				
				
      out.write("\n");
      out.write("\t\t\t<!-- Popular Products -->\n");
      out.write("        <div class=\"fr-pop-wrap\">\n");
      out.write("  \n");
      out.write("            <h3 class=\"component-ttl\" style=\"font-family: serif\"><span>sản phẩm giảm giá</span></h3>\n");
      out.write("          \n");
      out.write("            <ul class=\"fr-pop-tabs sections-show\">\n");
      out.write("                <li><a data-frpoptab-num=\"1\" data-frpoptab=\"#frpoptab-tab-1\" href=\"#\" class=\"active\">Tất cả sản phẩm</a></li>\n");
      out.write("                <li><a data-frpoptab-num=\"2\" data-frpoptab=\"#frpoptab-tab-2\" href=\"#\">Xiaomi</a></li>\n");
      out.write("                <li><a data-frpoptab-num=\"3\" data-frpoptab=\"#frpoptab-tab-3\" href=\"#\">Iphone</a></li>\n");
      out.write("                <li><a data-frpoptab-num=\"4\" data-frpoptab=\"#frpoptab-tab-4\" href=\"#\">Oppo</a></li>\n");
      out.write("                <div style=\"float: right; margin: 0;padding: 12px; font-size: 18px; text-transform: uppercase; background-color: lavender;\">\n");
      out.write("\t\t\t<p style=\"margin:0\">");
      out.print(promotion.getReason() );
      out.write(' ');
      out.write('(');
      out.write(' ');
      out.print(promotion.getDateStart() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(promotion.getDateEnd() );
      out.write(" )</p>\n");
      out.write("            </div>\n");
      out.write("            </ul>\n");
      out.write("         \n");
      out.write("      </div>\n");
      out.write("             <div class=\"fr-pop-tab-cont\">\n");
      out.write("\n");
      out.write("                <p data-frpoptab-num=\"1\" class=\"fr-pop-tab-mob active\" data-frpoptab=\"#frpoptab-tab-1\">Tất cả </p>\n");
      out.write("                <div class=\" prod-items fr-pop-tab\" id=\"frpoptab-tab-1\">\n");
      out.write("\n");
      out.write("                 <ul style=\"padding: 0;width: 101%;list-style: none;\">\n");
      out.write("\t\t\t\t\t\t\t");

						listProduct = productDAO.listProductbyPromotion();
							for (int i = 0; i < listProduct.size(); i++) {
								String name= listProduct.get(i).getName();
								String image= listProduct.get(i).getImage();
								int percent_promotion=listProduct.get(i).getPercent_promotion();
								int price=listProduct.get(i).getPrice();
								int new_product=listProduct.get(i).getNew_product();
						
      out.write("\n");
      out.write("\t\t\t\t\t\t <li class=\"prod-i loadMore1\">\n");
      out.write("                            <div class=\"prod-i-top\">\n");
      out.write("                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write("\" class=\"prod-i-img\"><!-- NO SPACE -->\n");
      out.write("                                <img  src=\"");
      out.print(image);
      out.write("\" alt=\"\"><!-- NO SPACE --></a> \n");
      out.write("                        \t\t\n");
      out.write("                            </div>\n");
      out.write("                            <h3>\n");
      out.write("                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write('"');
      out.write('>');
      out.print(name);
      out.write("</a>\n");
      out.write("                            </h3>\n");
      out.write("                            <p class=\"prod-i-price\">\n");
      out.write("                            ");
int a= price-price*percent_promotion/100;
      out.write("\n");
      out.write("                                <b>");
      out.print(formatter.format(a) );
      out.write("₫</b>\n");
      out.write("                                 (<strike><b>");
      out.print(formatter.format(price) );
      out.write("₫</b></strike>)\n");
      out.write("                            </p>\n");
      out.write("                             <div class=\"prod-sticker\">\n");
      out.write("                                    <p class=\"prod-sticker-3\">-");
      out.print(percent_promotion );
      out.write("%</p>\n");
      out.write("                                </div>\n");
      out.write("                                ");
if(new_product==1){ 
      out.write("\n");
      out.write("                                <div class=\"prod-sticker1\">\n");
      out.write("                                    <p class=\"prod-sticker-1\">NEW</p>\n");
      out.write("                                </div>  \n");
      out.write("                                ");
} 
      out.write("\n");
      out.write("                          \n");
      out.write("                        </li>\n");
      out.write("                        ");
} 
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("                   <div class=\"clear-float\"></div>\n");
      out.write("\t\t\t\t\t<p class=\"loadMore\" id=\"loadMore1\">Xem thêm <i class=\"fas fa-chevron-right\"></i></p>\n");
      out.write("                 \n");
      out.write("                </div>\n");
      out.write("                 <p data-frpoptab-num=\"2\" class=\"fr-pop-tab-mob\" data-frpoptab=\"#frpoptab-tab-2\">Xiaomi</p>\n");
      out.write("                <div class=\" prod-items fr-pop-tab\" id=\"frpoptab-tab-2\">\n");
      out.write("\n");
      out.write("                  <ul style=\"padding: 0;width: 101%;list-style: none;\">\n");
      out.write("\t\t\t\t\t\t\t");

						listProduct = productDAO.listProductbyPromotionBrand(3);
							for (int i = 0; i < listProduct.size(); i++) {
								String name= listProduct.get(i).getName();
								String image= listProduct.get(i).getImage();
								int percent_promotion=listProduct.get(i).getPercent_promotion();
								int price=listProduct.get(i).getPrice();
								int new_product=listProduct.get(i).getNew_product();
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t <li class=\"prod-i\">\n");
      out.write("\t\t                            <div class=\"prod-i-top\">\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write("\" class=\"prod-i-img\"><!-- NO SPACE -->\n");
      out.write("\t\t                                <img  src=\"");
      out.print(image);
      out.write("\" alt=\"\"><!-- NO SPACE --></a> \n");
      out.write("\t\t                        \t\t\n");
      out.write("\t\t                            </div>\n");
      out.write("\t\t                            <h3>\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write('"');
      out.write('>');
      out.print(name);
      out.write("</a>\n");
      out.write("\t\t                            </h3>\n");
      out.write("\t\t                            <p class=\"prod-i-price\">\n");
      out.write("\t\t                            ");
int a= price-price*percent_promotion/100;
      out.write("\n");
      out.write("\t\t                                <b>");
      out.print(formatter.format(a) );
      out.write("₫</b>\n");
      out.write("\t\t                                 (<strike><b>");
      out.print(formatter.format(price) );
      out.write("₫</b></strike>)\n");
      out.write("\t\t                            </p>\n");
      out.write("\t\t                             <div class=\"prod-sticker\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-3\">-");
      out.print(percent_promotion );
      out.write("%</p>\n");
      out.write("\t\t                                </div>\n");
      out.write("\t\t                                ");
if(new_product==1){ 
      out.write("\n");
      out.write("\t\t                                <div class=\"prod-sticker1\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-1\">NEW</p>\n");
      out.write("\t\t                                </div>  \n");
      out.write("\t\t                                ");
} 
      out.write("\n");
      out.write("\t\t                          \n");
      out.write("\t\t                        </li>\n");
      out.write("\t\t                        ");
} 
      out.write("\n");
      out.write("\t\t                    </ul>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <p data-frpoptab-num=\"3\" class=\"fr-pop-tab-mob\" data-frpoptab=\"#frpoptab-tab-3\">Iphone</p>\n");
      out.write("                <div class=\" prod-items fr-pop-tab\" id=\"frpoptab-tab-3\">\n");
      out.write("\n");
      out.write("                  <ul style=\"padding: 0;width: 101%;list-style: none;\">\n");
      out.write("\t\t\t\t\t\t\t");

						listProduct = productDAO.listProductbyPromotionBrand(4);
							for (int i = 0; i < listProduct.size(); i++) {
								String name= listProduct.get(i).getName();
								String image= listProduct.get(i).getImage();
								int percent_promotion=listProduct.get(i).getPercent_promotion();
								int price=listProduct.get(i).getPrice();
								int new_product=listProduct.get(i).getNew_product();
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t <li class=\"prod-i\">\n");
      out.write("\t\t                            <div class=\"prod-i-top\">\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write("\" class=\"prod-i-img\"><!-- NO SPACE -->\n");
      out.write("\t\t                                <img  src=\"");
      out.print(image);
      out.write("\" alt=\"\"><!-- NO SPACE --></a> \n");
      out.write("\t\t                        \t\t\n");
      out.write("\t\t                            </div>\n");
      out.write("\t\t                            <h3>\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write('"');
      out.write('>');
      out.print(name);
      out.write("</a>\n");
      out.write("\t\t                            </h3>\n");
      out.write("\t\t                            <p class=\"prod-i-price\">\n");
      out.write("\t\t                            ");
int a= price-price*percent_promotion/100;
      out.write("\n");
      out.write("\t\t                                <b>");
      out.print(formatter.format(a) );
      out.write("₫</b>\n");
      out.write("\t\t                                 (<strike><b>");
      out.print(formatter.format(price) );
      out.write("₫</b></strike>)\n");
      out.write("\t\t                            </p>\n");
      out.write("\t\t                             <div class=\"prod-sticker\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-3\">-");
      out.print(percent_promotion );
      out.write("%</p>\n");
      out.write("\t\t                                </div>\n");
      out.write("\t\t                                ");
if(new_product==1){ 
      out.write("\n");
      out.write("\t\t                                <div class=\"prod-sticker1\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-1\">NEW</p>\n");
      out.write("\t\t                                </div>  \n");
      out.write("\t\t                                ");
} 
      out.write("\n");
      out.write("\t\t                          \n");
      out.write("\t\t                        </li>\n");
      out.write("\t\t                        ");
} 
      out.write("\n");
      out.write("\t\t                    </ul>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <p data-frpoptab-num=\"4\" class=\"fr-pop-tab-mob\" data-frpoptab=\"#frpoptab-tab-4\">Oppo</p>\n");
      out.write("                <div class=\" prod-items fr-pop-tab\" id=\"frpoptab-tab-4\">\n");
      out.write("\n");
      out.write("                  <ul style=\"padding: 0;width: 101%;list-style: none;\">\n");
      out.write("\t\t\t\t\t\t\t");

						listProduct = productDAO.listProductbyPromotionBrand(5);
							for (int i = 0; i < listProduct.size(); i++) {
								String name= listProduct.get(i).getName();
								String image= listProduct.get(i).getImage();
								int percent_promotion=listProduct.get(i).getPercent_promotion();
								int price=listProduct.get(i).getPrice();
								int new_product=listProduct.get(i).getNew_product();
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t <li class=\"prod-i\">\n");
      out.write("\t\t                            <div class=\"prod-i-top\">\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write("\" class=\"prod-i-img\"><!-- NO SPACE -->\n");
      out.write("\t\t                                <img  src=\"");
      out.print(image);
      out.write("\" alt=\"\"><!-- NO SPACE --></a> \n");
      out.write("\t\t                        \t\t\n");
      out.write("\t\t                            </div>\n");
      out.write("\t\t                            <h3>\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write('"');
      out.write('>');
      out.print(name);
      out.write("</a>\n");
      out.write("\t\t                            </h3>\n");
      out.write("\t\t                            <p class=\"prod-i-price\">\n");
      out.write("\t\t                            ");
int a= price-price*percent_promotion/100;
      out.write("\n");
      out.write("\t\t                                <b>");
      out.print(formatter.format(a) );
      out.write("₫</b>\n");
      out.write("\t\t                                 (<strike><b>");
      out.print(formatter.format(price) );
      out.write("₫</b></strike>)\n");
      out.write("\t\t                            </p>\n");
      out.write("\t\t                             <div class=\"prod-sticker\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-3\">-");
      out.print(percent_promotion );
      out.write("%</p>\n");
      out.write("\t\t                                </div>\n");
      out.write("\t\t                                ");
if(new_product==1){ 
      out.write("\n");
      out.write("\t\t                                <div class=\"prod-sticker1\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-1\">NEW</p>\n");
      out.write("\t\t                                </div>  \n");
      out.write("\t\t                                ");
} 
      out.write("\n");
      out.write("\t\t                          \n");
      out.write("\t\t                        </li>\n");
      out.write("\t\t                        ");
} 
      out.write("\n");
      out.write("\t\t                    </ul>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                </div>\n");
      out.write("   \t\t<!-- NEW Products -->\n");
      out.write("        <div class=\"fr-pop-wrap\">\n");
      out.write("\n");
      out.write("            <h3 class=\"component-ttl\" style=\"font-family: serif\"><span>sản phẩm mới</span></h3>\n");
      out.write("\n");
      out.write("            <ul class=\"fr-pop-tabs sections-show\">\n");
      out.write("                <li><a data-frpoptab-num=\"21\" data-frpoptab=\"#frpoptab-tab-21\" href=\"#\" class=\"active\">Tất cả sản phẩm</a></li>\n");
      out.write("                <li><a data-frpoptab-num=\"22\" data-frpoptab=\"#frpoptab-tab-22\" href=\"#\">Xiaomi</a></li>\n");
      out.write("                <li><a data-frpoptab-num=\"23\" data-frpoptab=\"#frpoptab-tab-23\" href=\"#\">Iphone</a></li>\n");
      out.write("                <li><a data-frpoptab-num=\"24\" data-frpoptab=\"#frpoptab-tab-24\" href=\"#\">Oppo</a></li>\n");
      out.write("            </ul>\n");
      out.write("     <!--        <p class=\"loadMore\" id=\"loadMore3\"><i class=\"fas fa-chevron-down\"></i></p>\n");
      out.write("\t\t\t<p class=\"loadMore\" id=\"loadLess3\"><i class=\"fas fa-chevron-up\"></i></p>\n");
      out.write("      -->       \n");
      out.write("      </div>\n");
      out.write("             <div class=\"fr-pop-tab-cont\">\n");
      out.write("\n");
      out.write("                <p data-frpoptab-num=\"21\" class=\"fr-pop-tab-mob active\" data-frpoptab=\"#frpoptab-tab-21\">Tất cả </p>\n");
      out.write("                <div class=\" prod-items fr-pop-tab\" id=\"frpoptab-tab-21\">\n");
      out.write("\n");
      out.write("                 <ul style=\"padding: 0;width: 101%;list-style: none;\">\n");
      out.write("\t\t\t\t\t\t\t");

						listProduct = productDAO.listProductNew();
							for (int i = 0; i < listProduct.size(); i++) {
								String name= listProduct.get(i).getName();
								String image= listProduct.get(i).getImage();
								int percent_promotion=listProduct.get(i).getPercent_promotion();
								int price=listProduct.get(i).getPrice();
								int new_product=listProduct.get(i).getNew_product();
						
      out.write("\n");
      out.write("\t\t\t\t\t\t <li class=\"prod-i loadMore2 \">\n");
      out.write("                            <div class=\"prod-i-top\">\n");
      out.write("                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write("\" class=\"prod-i-img\"><!-- NO SPACE -->\n");
      out.write("                                <img  src=\"");
      out.print(image);
      out.write("\" alt=\"\"><!-- NO SPACE --></a> \n");
      out.write("                        \t\t\n");
      out.write("                            </div>\n");
      out.write("                            <h3>\n");
      out.write("                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write('"');
      out.write('>');
      out.print(name);
      out.write("</a>\n");
      out.write("                            </h3>\n");
      out.write("                            ");
 if(percent_promotion>0){ 
      out.write("\n");
      out.write("                            <p class=\"prod-i-price\">\n");
      out.write("                            ");
int a= price-price*percent_promotion/100;
      out.write("\n");
      out.write("                                <b>");
      out.print(formatter.format(a) );
      out.write("₫</b>\n");
      out.write("                                 (<strike><b>");
      out.print(formatter.format(price) );
      out.write("₫</b></strike>)\n");
      out.write("                            </p>\n");
      out.write("                             <div class=\"prod-sticker\">\n");
      out.write("                                    <p class=\"prod-sticker-3\">-");
      out.print(percent_promotion );
      out.write("%</p>\n");
      out.write("                                </div>\n");
      out.write("                                 \n");
      out.write("                                ");
} else { 
      out.write("\n");
      out.write("                                <p class=\"prod-i-price\">\n");
      out.write("                                <b>");
      out.print(formatter.format(price));
      out.write("₫</b>\n");
      out.write("                            </p>\n");
      out.write("                                ");
}
      out.write("\n");
      out.write("                                ");
 if(new_product==1){ 
      out.write("\n");
      out.write("                                 <div class=\"prod-sticker1\">\n");
      out.write("                                    <p class=\"prod-sticker-1\">NEW</p>\n");
      out.write("                                </div>\n");
      out.write("                                ");
} 
      out.write("\n");
      out.write("                          \n");
      out.write("                        </li>\n");
      out.write("                        ");
} 
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("\t\t\t\t\t  <div class=\"clear-float\"></div>\n");
      out.write("\t\t\t\t\t<p class=\"loadMore\" id=\"loadMore2\">Xem thêm <i class=\"fas fa-chevron-right\"></i></p>\n");
      out.write("                 \n");
      out.write("                </div>\n");
      out.write("                 <p data-frpoptab-num=\"22\" class=\"fr-pop-tab-mob\" data-frpoptab=\"#frpoptab-tab-22\">Xiaomi</p>\n");
      out.write("                <div class=\" prod-items fr-pop-tab\" id=\"frpoptab-tab-22\">\n");
      out.write("\n");
      out.write("                  <ul style=\"padding: 0;width: 101%;list-style: none;\">\n");
      out.write("\t\t\t\t\t\t\t");

						listProduct = productDAO.listProductNewBrand(3);
							for (int i = 0; i < listProduct.size(); i++) {
								String name= listProduct.get(i).getName();
								String image= listProduct.get(i).getImage();
								int percent_promotion=listProduct.get(i).getPercent_promotion();
								int price=listProduct.get(i).getPrice();
								int new_product=listProduct.get(i).getNew_product();
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t <li class=\"prod-i\">\n");
      out.write("\t\t                            <div class=\"prod-i-top\">\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write("\" class=\"prod-i-img\"><!-- NO SPACE -->\n");
      out.write("\t\t                                <img  src=\"");
      out.print(image);
      out.write("\" alt=\"\"><!-- NO SPACE --></a> \n");
      out.write("\t\t                        \t\t\n");
      out.write("\t\t                            </div>\n");
      out.write("\t\t                            <h3>\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write('"');
      out.write('>');
      out.print(name);
      out.write("</a>\n");
      out.write("\t\t                            </h3>\n");
      out.write("\t\t                            ");
 if(percent_promotion>0){ 
      out.write("\n");
      out.write("\t\t                            <p class=\"prod-i-price\">\n");
      out.write("\t\t                            ");
int a= price-price*percent_promotion/100;
      out.write("\n");
      out.write("\t\t                                <b>");
      out.print(formatter.format(a) );
      out.write("₫</b>\n");
      out.write("\t\t                                 (<strike><b>");
      out.print(formatter.format(price) );
      out.write("₫</b></strike>)\n");
      out.write("\t\t                            </p>\n");
      out.write("\t\t                             <div class=\"prod-sticker\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-3\">-");
      out.print(percent_promotion );
      out.write("%</p>\n");
      out.write("\t\t                                </div>\n");
      out.write("\t\t                                 \n");
      out.write("\t\t                                ");
} else { 
      out.write("\n");
      out.write("\t\t                                <p class=\"prod-i-price\">\n");
      out.write("\t\t                                <b>");
      out.print(formatter.format(price) );
      out.write("₫</b>\n");
      out.write("\t\t                            </p>\n");
      out.write("\t\t                                ");
}
      out.write("\n");
      out.write("\t\t                                ");
 if(new_product==1){ 
      out.write("\n");
      out.write("\t\t                                 <div class=\"prod-sticker1\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-1\">NEW</p>\n");
      out.write("\t\t                                </div>\n");
      out.write("\t\t                                ");
} 
      out.write("\n");
      out.write("\t\t                          \n");
      out.write("\t\t                        </li>\n");
      out.write("\t\t                        ");
} 
      out.write("\n");
      out.write("\t\t                    </ul>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <p data-frpoptab-num=\"23\" class=\"fr-pop-tab-mob\" data-frpoptab=\"#frpoptab-tab-23\">Iphone</p>\n");
      out.write("                <div class=\" prod-items fr-pop-tab\" id=\"frpoptab-tab-23\">\n");
      out.write("\n");
      out.write("                  <ul style=\"padding: 0;width: 101%;list-style: none;\">\n");
      out.write("\t\t\t\t\t\t\t");

						listProduct = productDAO.listProductNewBrand(4);
							for (int i = 0; i < listProduct.size(); i++) {
								String name= listProduct.get(i).getName();
								String image= listProduct.get(i).getImage();
								int percent_promotion=listProduct.get(i).getPercent_promotion();
								int price=listProduct.get(i).getPrice();
								int new_product=listProduct.get(i).getNew_product();
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t <li class=\"prod-i\">\n");
      out.write("\t\t                            <div class=\"prod-i-top\">\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write("\" class=\"prod-i-img\"><!-- NO SPACE -->\n");
      out.write("\t\t                                <img  src=\"");
      out.print(image);
      out.write("\" alt=\"\"><!-- NO SPACE --></a> \n");
      out.write("\t\t                        \t\t\n");
      out.write("\t\t                            </div>\n");
      out.write("\t\t                            <h3>\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write('"');
      out.write('>');
      out.print(name);
      out.write("</a>\n");
      out.write("\t\t                            </h3>\n");
      out.write("\t\t                            ");
 if(percent_promotion>0){ 
      out.write("\n");
      out.write("\t\t                            <p class=\"prod-i-price\">\n");
      out.write("\t\t                            ");
int a= price-price*percent_promotion/100;
      out.write("\n");
      out.write("\t\t                                <b>");
      out.print(formatter.format(a) );
      out.write("₫</b>\n");
      out.write("\t\t                                 (<strike><b>");
      out.print(formatter.format(price) );
      out.write("₫</b></strike>)\n");
      out.write("\t\t                            </p>\n");
      out.write("\t\t                             <div class=\"prod-sticker\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-3\">-");
      out.print(percent_promotion );
      out.write("%</p>\n");
      out.write("\t\t                                </div>\n");
      out.write("\t\t                                 \n");
      out.write("\t\t                                ");
} else { 
      out.write("\n");
      out.write("\t\t                                <p class=\"prod-i-price\">\n");
      out.write("\t\t                                <b>");
      out.print(formatter.format(price) );
      out.write("₫</b>\n");
      out.write("\t\t                            </p>\n");
      out.write("\t\t                                ");
}
      out.write("\n");
      out.write("\t\t                                ");
 if(new_product==1){ 
      out.write("\n");
      out.write("\t\t                                 <div class=\"prod-sticker1\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-1\">NEW</p>\n");
      out.write("\t\t                                </div>\n");
      out.write("\t\t                                ");
} 
      out.write("\n");
      out.write("\t\t                          \n");
      out.write("\t\t                        </li>\n");
      out.write("\t\t                        ");
} 
      out.write("\n");
      out.write("\t\t                    </ul>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <p data-frpoptab-num=\"24\" class=\"fr-pop-tab-mob\" data-frpoptab=\"#frpoptab-tab-24\">Oppo</p>\n");
      out.write("                <div class=\" prod-items fr-pop-tab\" id=\"frpoptab-tab-24\">\n");
      out.write("\n");
      out.write("                  <ul style=\"padding: 0;width: 101%;list-style: none;\">\n");
      out.write("\t\t\t\t\t\t\t");

						listProduct = productDAO.listProductNewBrand(5);
							for (int i = 0; i < listProduct.size(); i++) {
								String name= listProduct.get(i).getName();
								String image= listProduct.get(i).getImage();
								int percent_promotion=listProduct.get(i).getPercent_promotion();
								int price=listProduct.get(i).getPrice();
								int new_product=listProduct.get(i).getNew_product();
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t <li class=\"prod-i\">\n");
      out.write("\t\t                            <div class=\"prod-i-top\">\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write("\" class=\"prod-i-img\"><!-- NO SPACE -->\n");
      out.write("\t\t                                <img  src=\"");
      out.print(image);
      out.write("\" alt=\"\"><!-- NO SPACE --></a> \n");
      out.write("\t\t                        \t\t\n");
      out.write("\t\t                            </div>\n");
      out.write("\t\t                            <h3>\n");
      out.write("\t\t                                <a href=\"Product.jsp?id=");
      out.print(listProduct.get(i).getId());
      out.write('"');
      out.write('>');
      out.print(name);
      out.write("</a>\n");
      out.write("\t\t                            </h3>\n");
      out.write("\t\t                            ");
 if(percent_promotion>0){ 
      out.write("\n");
      out.write("\t\t                            <p class=\"prod-i-price\">\n");
      out.write("\t\t                            ");
int a= price-price*percent_promotion/100;
      out.write("\n");
      out.write("\t\t                                <b>");
      out.print(formatter.format(a) );
      out.write("₫</b>\n");
      out.write("\t\t                                 (<strike><b>");
      out.print(formatter.format(price) );
      out.write("₫</b></strike>)\n");
      out.write("\t\t                            </p>\n");
      out.write("\t\t                             <div class=\"prod-sticker\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-3\">-");
      out.print(percent_promotion );
      out.write("%</p>\n");
      out.write("\t\t                                </div>\n");
      out.write("\t\t                                 \n");
      out.write("\t\t                                ");
} else { 
      out.write("\n");
      out.write("\t\t                                <p class=\"prod-i-price\">\n");
      out.write("\t\t                                <b>");
      out.print(formatter.format(price) );
      out.write("₫</b>\n");
      out.write("\t\t                            </p>\n");
      out.write("\t\t                                ");
}
      out.write("\n");
      out.write("\t\t                                ");
 if(new_product==1){ 
      out.write("\n");
      out.write("\t\t                                 <div class=\"prod-sticker1\">\n");
      out.write("\t\t                                    <p class=\"prod-sticker-1\">NEW</p>\n");
      out.write("\t\t                                </div>\n");
      out.write("\t\t                                ");
} 
      out.write("\n");
      out.write("\t\t                          \n");
      out.write("\t\t                        </li>\n");
      out.write("\t\t                        ");
} 
      out.write("\n");
      out.write("\t\t                    </ul>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t    <!-- Subscribe Form -->\n");
      out.write("        <div class=\"newsletter\">\n");
      out.write("            <h3>ĐĂNG KÍ VỚI CHÚNG TÔI</h3>\n");
      out.write("            <p>Điền email của bạn nếu muốn theo dõi các sản phẩm mới của chúng tôi</p>\n");
      out.write("            <form action=\"#\">\n");
      out.write("                <input placeholder=\"Email của bạn\" type=\"text\">\n");
      out.write("                <input name=\"OK\" value=\"Đăng kí\" type=\"submit\">\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- Footer - start -->\n");
      out.write("<footer class=\"footer-wrap\">\n");
      out.write("    <div class=\"container f-menu-list\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"f-menu\">\n");
      out.write("                <h3>\n");
      out.write("                   Hỗ trợ khách hàng\n");
      out.write("                </h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li>Monday-Sunday(9am-6pm)</li>\n");
      out.write("                    <li>Hotline đặt hàng: <span style=\"color:red; font-size:15px\">1900-1000</span></li>\n");
      out.write("                    <li>Hỗ trợ : <a href=\"#\">support@500ae.vn</a></li>\n");
      out.write("                    <li>Bảo mật : <a href=\"#\">security@500ae.vn</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("           \n");
      out.write("            <div class=\"f-menu\">\n");
      out.write("                <h3>\n");
      out.write("                   Về 500AE\n");
      out.write("                </h3>\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#\">Giới thiệu về 500AE</a></li>\n");
      out.write("                    <li><a href=\"#\">Chính sách bảo mật</a></li>\n");
      out.write("                    <li><a href=\"#\">Điều khoản sử dụng</a></li>\n");
      out.write("                    <li><a href=\"#\">Tuyển dụng</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"f-menu\">\n");
      out.write("                <h3>\n");
      out.write("                    Phương thức thanh toán\n");
      out.write("                </h3>\n");
      out.write("                <div>\n");
      out.write("                        <img class=\"img-boder\" src=\"../img/logo-png/005-visa.png\" alt=\"\">\n");
      out.write("                        <img class=\"img-boder\" src=\"../img/logo-png/006-jcb.png\" alt=\"\">\n");
      out.write("                        <img class=\"img-boder\" src=\"../img/logo-png/007-atm.png\" alt=\"\">\n");
      out.write("                        <img class=\"img-boder\" src=\"../img/logo-png/008-mastercard.png\" alt=\"\">\n");
      out.write("                        <img class=\"img-boder\" src=\"../img/logo-png/009-money.png\" alt=\"\">\n");
      out.write("                 \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"f-menu\">\n");
      out.write("            <h3>Ứng dụng trên điện thoại</h3>\n");
      out.write("             <img style=\"width:150px; height:auto\" src=\"../img/header/chplay.png\" alt=\"\">\n");
      out.write("             <img style=\"width:150px; height:auto\" src=\"../img/header/ios.png\" alt=\"\">\n");
      out.write("                       \n");
      out.write("            </div>\n");
      out.write("       \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\" footer-bottom\">\n");
      out.write("    \t<div class=\"row \">\n");
      out.write("                <ul class=\" container social-icons\">\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"http://facebook.com/\" rel=\"nofollow\" target=\"_blank\">\n");
      out.write("                            <i class=\"fab fa-facebook\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"http://google.com/\" rel=\"nofollow\" target=\"_blank\">\n");
      out.write("                            <i class=\"fab fa-google-plus\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"http://twitter.com/\" rel=\"nofollow\" target=\"_blank\">\n");
      out.write("                            <i class=\"fab fa-twitter\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"http://vk.com/\" rel=\"nofollow\" target=\"_blank\">\n");
      out.write("                            <i class=\"fab fa-vk\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"http://instagram.com/\" rel=\"nofollow\" target=\"_blank\">\n");
      out.write("                            <i class=\"fab fa-instagram\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("</footer>\n");
      out.write("<!-- Footer - end -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("<script src=\"../Js/main.js\"></script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
